name: Notify Container Repo

on:
  push:
    branches:
      - master  # or main

jobs:
  notify-container:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger container build
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.CONTAINER_TRIGGER_TOKEN }}" \
            https://api.github.com/repos/sanskrutipatil-Techlantern/microfrontend-container/dispatches \
            -d '{"event_type":"trigger-from-header"}'
